version: '3.9'
services:
  api:
    container_name: menu-api
    image: murtazox04/menu-api:0.0.1
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    env_file:
      - .env
    restart: always
    volumes:
      - ./:/app
    depends_on:
      - db
    networks:
      - api
    ports:
      - "8001:8000"  # Adjusted port to avoid conflict

  admin:
    container_name: menu-admin
    image: murtazx04/menu-admin:0.0.1
    build:
      context: .
      dockerfile: docker/admin/Dockerfile
    env_file:
      - .env
    restart: always
    depends_on:
      - db
    networks:
      - admin
    ports:
      - "8000:8000"

  db:
    container_name: menu-db
    image: postgres:latest
    environment:
      POSTGRES_DB: menu_service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - api
      - admin
    restart: unless-stopped

networks:
  api:
  admin:

volumes:
  db:
