version: '3.9'
services:
  api:
    container_name: menu-api
    image: murtazox04/menu-api:0.0.1
    build:
      context: ./
    env_file:
      - .env
    command: poetry run python -m app.api
    restart: always
    depends_on:
      - db
    networks:
      - api
    ports:
      - "8000:8001"

  db:
    container_name: menu-db
    image: postgres:latest
    environment:
      POSTGRES_DB: menu_service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - api
    restart: unless-stopped


networks:
  api:

volumes:
  db:
