# Generated by Django 5.0.6 on 2024-07-01 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('is_verified', models.BooleanField(blank=True, default=False, null=True)),
                ('address', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('working_time', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField()),
                ('phone_number', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'restaurants',
                'managed': False,
            },
        ),
    ]
