"""Fixed bugs in model relationship

Revision ID: 4d02e7c92dbb
Revises: 5e045c0b8abe
Create Date: 2024-06-26 09:26:52.128928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4d02e7c92dbb'
down_revision: Union[str, None] = '5e045c0b8abe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dish_parameters',
    sa.Column('dish_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dish_id'], ['dishes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('product_parameters')
    op.alter_column('cart_items', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('cart_items_association', 'cart_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('cart_items_association', 'cart_item_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('discounts', 'start_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('discounts', 'end_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('discounts', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('dishes', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('dishes', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('dishes', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('menu_categories', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('menu_categories', 'restaurant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('restaurants', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('restaurants', 'is_verified',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('restaurants', 'is_verified',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('restaurants', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('menu_categories', 'restaurant_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('menu_categories', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('dishes', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('dishes', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('dishes', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('discounts', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('discounts', 'end_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('discounts', 'start_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('cart_items_association', 'cart_item_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('cart_items_association', 'cart_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('cart_items', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_table('product_parameters',
    sa.Column('dish_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('key', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('value', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['dish_id'], ['dishes.id'], name='product_parameters_dish_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='product_parameters_pkey')
    )
    op.drop_table('dish_parameters')
    # ### end Alembic commands ###
