"""Fixed bugs in model relationship

Revision ID: 5e045c0b8abe
Revises: 621078d3739c
Create Date: 2024-06-26 09:22:56.169644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e045c0b8abe'
down_revision: Union[str, None] = '621078d3739c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
