"""Update models

Revision ID: 621078d3739c
Revises: 7e21686ffc24
Create Date: 2024-06-25 19:08:47.844839

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '621078d3739c'
down_revision: Union[str, None] = '7e21686ffc24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cart_items_association',
    sa.Column('cart_id', sa.Integer(), nullable=True),
    sa.Column('cart_item_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cart_id'], ['carts.id'], ),
    sa.ForeignKeyConstraint(['cart_item_id'], ['cart_items.id'], )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cart_items_association')
    # ### end Alembic commands ###
