"""Fixed bugs in model relationship

Revision ID: c691cdb6a7fa
Revises: 4d02e7c92dbb
Create Date: 2024-06-26 09:32:16.246343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c691cdb6a7fa'
down_revision: Union[str, None] = '4d02e7c92dbb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('restaurants', 'is_verified',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('restaurants', 'address',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('restaurants', 'latitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('restaurants', 'longitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('restaurants', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('restaurants', 'phone_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('restaurants', 'phone_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('restaurants', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('restaurants', 'longitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('restaurants', 'latitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('restaurants', 'address',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('restaurants', 'is_verified',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###
