apiVersion: apps/v1
kind: Deployment
metadata:
  name: menu-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: menu-api
  template:
    metadata:
      labels:
        app: menu-api
    spec:
      containers:
      - name: api
        image: murtazox04/menu-api:0.0.1
        ports:
        - containerPort: 8001
        env:
        - name: POSTGRES_DB
          value: "menu_service"
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "1234"
